### ISSUE TITLE
Requires root to work

### ISSUE THREAD

**Issue by lululock71** [alesya-h/linux_detect_tablet_mode#23]
Hi,
The script requires root privileges because it uses xinit...
So I can't have it started from my .xinitrc file at logon.
Is there a way to quickly fix this ?

**Comment by alesguzik** [comment]
Hi. It doesn't use xinit (I can't even think of why it would use it) and it doesn't require root. It needs access to input devices, but for that you would just need to add your user to the `input` group.  It does work when started from .xinitrc - I used it myself that way and other users also run it this way. You may have seen `xinput` rather than `xinit` but that is not part of the script but rather a part of an example configuration - it is used to enable/disable keyboard and touchpad when switching between tablet and normal modes. It doesn't require root either, but you might want to update it's parameters to match your hardware.

**Comment by lululock71** [comment]
Hi,
I was dumb and forgot to add the user into the input group. And yeah, I wrote "xinit" while I meant "xinput". Sorry for making you loose time and I appreciate you took the time to answer a such dumb question. I was tired, read too fast and missed steps. It works flawlessly now on my Yoga 370. Any place where I can put the config file for others to use it ?

**Comment by coldspark29** [comment]
@alesya-h It requires root for me as well, althoug I am in the input and tablet group. Can you please look into this?
