### ISSUE TITLE
Support for ENVY x360

### ISSUE THREAD

**Issue by acerspyro** [alesya-h/linux_detect_tablet_mode#26]
Devices:
* HP ENVY x360 (All sizes)
* HP Spectre x360 (All sizes)

It seems like the method for detecting whether the device is in laptop, tent, kiosk or tablet mode isn't working, however I have tested and confirmed that the keyboard gets disabled on Windows 10 if the hinge goes past 180 degrees, so it is possible.

As of right now, the keyboard only gets disabled once the hinge reaches 360 degrees (tablet mode), but this seems to be a firmware thing as tablet mode is still not triggered on KDE or GNOME on Ubuntu and Fedora using Wayland.

Device orientation using hid-recorder works.

![image](https://user-images.githubusercontent.com/4400999/177215398-586425d5-f071-413e-a45b-5708e458887b.png)

The thing is, changes to the hinge's position is not reflected in `libinput debug-events`, so it'll have to be fetched from elsewhere.

I have an HP ENVY x360 13 inch and an HP ENVY x360 15 inch (both from 2021) to test.

**Comment by alesya-h** [comment]
This project is not responsible for the hardware. It's just meant to add support for handling state transitions to lightweight desktop setups, that you have out of the box in GNOME and KDE. You might want to look at the older version of the project that used accelerometers (it's in the `old` directory of the project), but I am not sure it will help. Most likely someone would need to add support for those laptops in the kernel's input subsystem, so that correct input events are generated. That will make it work in GNOME and KDE, as well as in this script.
